### ISSUE TITLE
Do you accept external contibutors?

### ISSUE THREAD

**Issue by Polyterative** [this-is-learning/rxjs-fundamentals-course#13]
I love RXJS and have been using it in angular for the past 5 years. I would love to contribute with my experience. Where do I start?

**Comment by LayZeeDK** [comment]
Hi @Polyterative,

Please send me a DM on [Twitter](https://twitter.com/LayZeeDK) and I'll invite you to our private Discord server so that we can all more easily keep in touch.

Other than that, please look at current work in our GitHub Discussions:
https://github.com/this-is-learning/rxjs-fundamentals-course/discussions
